### PR TITLE
fix(router, admin): Admin Swagger headers and route paths

### LINKED ISSUE #80: [BUG] Admin Swagger uses User Security Headers
**Describe the bug**
SwaggerGenerator currently hardcodes the following non-admin headers as its header security scheme:
- security client id
- security client secret
- Bearer user token

Admin routes require masterkey and a JWT prefixed admin token instead.

**To Reproduce**
1. Go to `/admin/swagger`
2. Click on 'Authorize'
3. Notice the incorrect headers

**Expected behavior**
Each Swagger instance should expose the appropriate headers.
Pass a securityScheme object to SwaggerGenerator through RestController.

### PR DESCRIPTION
**Pull request by kon14**
Closes #80 and generally improves Swagger route doc generation.
- Admin routes are now properly prefixed by `/admin/` so that Swagger users no longer need to guess the proper baseUrl.
- Admin routes now require proper admin headers.

This PR also converts Admin router's `Authentication` header format from `JWT adminToken` to `Bearer adminToken`.
This change improves compatibility with OpenAPI and Swagger, while also improving consistency with user authentication.

This bit is not a breaking change as backwards compatibility has been preserved.

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the `main` branch
- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx`, where "xxx" is the issue number)

### CODE REVIEW

**Comment by kon14** [comment]
`any` types due to pre-existing routeDoc missing a type. Could technically add a type for that one tho.

File: packages/router/src/controllers/Rest/Swagger.ts [hunk 1]
```diff
@@ -69,12 +67,7 @@ export class SwaggerGenerator {
           },
         },
       },
-      security: [
-        {
-          clientid: [],
-          clientSecret: [],
-        },
-      ],
+      security: JSON.parse(JSON.stringify(this._routerMetadata.globalSecurityHeaders)),
```
Comment (kon14) [inline packages/router/src/controllers/Rest/Swagger.ts:70]: We could also entirely avoid repeated stringifications by just passing a pre-stringified `globalSecurityHeaders` instead. Totally type hacky, but definitely worth it perf-wise.

Comment (kon14) [reply packages/router/src/controllers/Rest/Swagger.ts]: Ended up stringifying once per Swagger construction instead (that makes 2 times total).

**Review by kkopanidis — APPROVED** [review]
