### PR TITLE
fix(router): excessive REST router refreshes

### LINKED ISSUE #89: [BUG] Redundant REST router refreshes
**Describe the bug**
REST router currently refreshes excessively due to `refreshRouter()` directly refreshing the Express router instead of scheduling a refresh based on a timeout, much like `registerRoute()` and `registerConduitRoute()` already do.

**To Reproduce**
1. Set a breakpoint in REST controller's `refreshRouter()`
2. Debug Core by itself
3. Notice excessive refreshes

N of refresh calls would differ based on previously registered routes, but on a fresh Redis state it should be 1.

**Expected behavior**
`refreshRouter()` should schedule a router refresh instead of directly refreshing Express.

### PR DESCRIPTION
**Pull request by kon14**
**What kind of change does this PR introduce?**
Fixes #89.

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `main` branch
- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx`, where "xxx" is the issue number)

### CODE REVIEW

File: packages/router/src/controllers/Rest/Rest.ts [hunk 1]
```diff
@@ -27,10 +27,6 @@ export class RestController extends ConduitRouter {
   private _swagger: SwaggerGenerator;
   private _scheduledTimeout: any = null;
 
-  get registeredRoutes() {
```
Comment (kon14) [inline packages/router/src/controllers/Rest/Rest.ts:30]: That was unused for a while.

**Comment by kon14** [comment]
Moved common derived class functionality into ConduitRouter base class.

**Review by kkopanidis — APPROVED** [review]
